### ISSUE TITLE
optool error

### ISSUE THREAD

**Issue by PsychoticMan** [CokePokes/PhantomLite#19]
Was able to cd to the PhantomFile_vX.Y but when I put in the command line optool install -c load -p "@executable_path/genghisChron.dylib" -t /Downloads/SnapchatCracked/Payload/Snapchat.app/Snapchat
i get the -bash: optool: command not found. Am I doing something wrong?

**Comment by clementh44** [comment]
Try  ./optool

**Comment by PsychoticMan** [comment]
With the ./optool command I do not get an error. Is it suppose to say anything after that?

**Comment by clementh44** [comment]
A good answer [here](https://stackoverflow.com/questions/6331075/why-do-you-need-dot-slash-before-script-name-to-run-it-in-bash).
The README should be updated with this.
