### ISSUE TITLE
Crash with v2.5 and 2.6

### ISSUE THREAD

**Issue by clementh44** [CokePokes/PhantomLite#24]
I tried snapchat v10.20.1.1 v10.20.0.5 and v10.19.0.2 with Cydia Impactor v0.9.42 and ios 11.1 on iPhone 6s : the application crashes at startup

Edit : same with 2.6 and snapchat 10.20.1.1 10.20.0.5

**Comment by clementh44** [comment]
fixed with 2.7

**Comment by JeffreyBytes** [comment]
@clementh44 I'm having this issue now with 2.7 snapchat 10.20.1.1. Any ideas?

**Comment by clementh44** [comment]
As you can see, I tried everything and I don't know why it's working for me with 2.7.
I also tried to reinstall the extender without success.
Good luck...
